package main.java.MovieTicket.servlet;

import main.java.MovieTicket.model.Movie;
import main.java.MovieTicket.util.MovieFileHandler;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

@WebServlet("/add-movie")
public class AddMovieServlet extends HttpServlet {

        /**
         * Handles GET /add-movie
         * Simply forwards to the add movie form.
         */
        @Override
        protected void doGet(HttpServletRequest request, HttpServletResponse response)
                throws ServletException, IOException {

            request.getRequestDispatcher("/WEB-INF/views/add-movie.jsp")
                    .forward(request, response);
        }

        /**
         * Handles POST /add-movie
         * Reads form fields, validates them, builds a Movie object,
         * saves it via MovieFileHandler, then redirects to the movie list.
         */
        @Override
        protected void doPost(HttpServletRequest request, HttpServletResponse response)
                throws ServletException, IOException {

            request.setCharacterEncoding("UTF-8");

            // ── 1. Read form parameters ───────────────────────────────────────────
            String title     = request.getParameter("title");
            String genre     = request.getParameter("genre");
            String durationStr  = request.getParameter("durationMinutes");
            String language  = request.getParameter("language");
            String rating    = request.getParameter("rating");
            String priceStr  = request.getParameter("ticketPrice");
            String available = request.getParameter("available");  // "true" or "false"

            // ── 2. Basic validation ───────────────────────────────────────────────
            if (isBlank(title) || isBlank(genre) || isBlank(durationStr)
                    || isBlank(language) || isBlank(rating) || isBlank(priceStr)) {

                request.setAttribute("errorMsg", "All fields are required.");
                request.setAttribute("title",    title);
                request.setAttribute("genre",    genre);
                request.setAttribute("language", language);
                request.setAttribute("rating",   rating);
                request.setAttribute("priceStr", priceStr);
                request.setAttribute("durationStr", durationStr);
                request.getRequestDispatcher("/WEB-INF/views/add-movie.jsp")
                        .forward(request, response);
                return;
            }

            // ── 3. Parse numeric fields ───────────────────────────────────────────
            int    duration;
            double price;
            try {
                duration = Integer.parseInt(durationStr.trim());
                price    = Double.parseDouble(priceStr.trim());
            } catch (NumberFormatException e) {
                request.setAttribute("errorMsg", "Duration must be a whole number and price must be a valid number.");
                request.getRequestDispatcher("/WEB-INF/views/add-movie.jsp")
                        .forward(request, response);
                return;
            }

            if (duration <= 0 || price < 0) {
                request.setAttribute("errorMsg", "Duration must be greater than 0 and price cannot be negative.");
                request.getRequestDispatcher("/WEB-INF/views/add-movie.jsp")
                        .forward(request, response);
                return;
            }

            // ── 4. Build Movie object (ID auto-generated by MovieFileHandler) ─────
            Movie movie = new Movie(
                    null,                              // ID will be generated
                    title.trim(),
                    genre.trim(),
                    duration,
                    language.trim(),
                    rating.trim(),
                    price,
                    "true".equals(available)
            );

            // ── 5. Save to file ───────────────────────────────────────────────────
            boolean saved = MovieFileHandler.addMovie(movie);

            if (saved) {
                request.getSession().setAttribute("successMsg",
                        "Movie \"" + movie.getTitle() + "\" added successfully!");
            } else {
                request.getSession().setAttribute("errorMsg",
                        "Something went wrong while saving the movie. Please try again.");
            }

            // ── 6. Redirect to movie list (PRG pattern prevents double-submit) ────
            response.sendRedirect(request.getContextPath() + "/movies");
        }

        // ── Helper ────────────────────────────────────────────────────────────────

        private boolean isBlank(String value) {
            return value == null || value.trim().isEmpty();
        }
}

